// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
	name: "abseil-cpp",
	platforms: [
		.iOS(.v12),
		.macOS(.v10_13),
		.macCatalyst(.v13),
		.watchOS(.v5),
		.tvOS(.v11)
	],
	products: [
		.library(name: "libabsl", targets: ["libabsl"]),
		.library(name: "absl_base", targets: ["absl_base"]),
		.library(name: "absl_string_view", targets: ["absl_string_view"]),
		.library(name: "absl_types", targets: ["absl_types"]),
	],
	targets: [
		.target(
			name: "absl_base",
			path: "absl/base",
			sources: [
				"internal/cycleclock.cc",
				"internal/low_level_alloc.cc",
				"internal/raw_logging.cc",
				"internal/scoped_set_env.cc",
				"internal/spinlock.cc",
				"internal/spinlock_wait.cc",
				"internal/strerror.cc",
				"internal/sysinfo.cc",
				"internal/thread_identity.cc",
				"internal/throw_delegate.cc",
				"internal/unscaledcycleclock.cc",
				"log_severity.cc",
			],
			publicHeadersPath: "include"
		),
		.target(
			name: "absl_string_view",
			dependencies: [
				"absl_base"
			],
			path: "absl/strings",
			sources: [
				"string_view.cc"
			],
			publicHeadersPath: "include"
		),
		.target(
			name: "absl_time_internal",
			dependencies: [
				"absl_base"
			],
			path: "absl/time/internal",
			sources: [
				"test_util.cc",
				"cctz/src/civil_time_detail.cc",
				"cctz/src/time_zone_fixed.cc",
				"cctz/src/time_zone_format.cc",
				"cctz/src/time_zone_if.cc",
				"cctz/src/time_zone_impl.cc",
				"cctz/src/time_zone_info.cc",
				"cctz/src/time_zone_libc.cc",
				"cctz/src/time_zone_lookup.cc",
				"cctz/src/time_zone_posix.cc",
				"cctz/src/zone_info_source.cc",
			],
			publicHeadersPath: "include",
			cSettings: [
				.headerSearchPath("../../../")
			],
			linkerSettings: [
				.linkedFramework("CoreFoundation")
			]
		),
		.target(
			name: "absl_types",
			dependencies: [
				"absl_base",
			],
			path: "absl/types",
			sources: [
				"bad_any_cast.cc",
				"bad_optional_access.cc",
				"bad_variant_access.cc",
			],
			publicHeadersPath: "include",
			cSettings: [
				.headerSearchPath("../../")
			]
		),
		.target(
			name: "libabsl",
			dependencies: [
				"absl_base",
				"absl_string_view",
				"absl_time_internal",
				"absl_types",
			],
			path: ".",
			sources: [
				"absl/container/internal/hashtablez_sampler.cc",
				"absl/container/internal/hashtablez_sampler_force_weak_definition.cc",
				"absl/container/internal/raw_hash_set.cc",
				"absl/crc/crc32c.cc",
				"absl/crc/internal/cpu_detect.cc",
				"absl/crc/internal/crc.cc",
				"absl/crc/internal/crc_cord_state.cc",
				"absl/crc/internal/crc_memcpy_fallback.cc",
				"absl/crc/internal/crc_memcpy_x86_arm_combined.cc",
				"absl/crc/internal/crc_non_temporal_memcpy.cc",
				"absl/crc/internal/crc_x86_arm_combined.cc",
				"absl/debugging/failure_signal_handler.cc",
				"absl/debugging/internal/address_is_readable.cc",
				"absl/debugging/internal/demangle.cc",
				"absl/debugging/internal/elf_mem_image.cc",
				"absl/debugging/internal/examine_stack.cc",
				"absl/debugging/internal/stack_consumption.cc",
				"absl/debugging/internal/vdso_support.cc",
				"absl/debugging/leak_check.cc",
				"absl/debugging/stacktrace.cc",
				"absl/debugging/symbolize.cc",
				"absl/flags/commandlineflag.cc",
				"absl/flags/flag.cc",
				"absl/flags/internal/commandlineflag.cc",
				"absl/flags/internal/flag.cc",
				"absl/flags/internal/private_handle_accessor.cc",
				"absl/flags/internal/program_name.cc",
				"absl/flags/internal/usage.cc",
				"absl/flags/marshalling.cc",
				"absl/flags/parse.cc",
				"absl/flags/reflection.cc",
				"absl/flags/usage.cc",
				"absl/flags/usage_config.cc",
				"absl/hash/internal/city.cc",
				"absl/hash/internal/hash.cc",
				"absl/hash/internal/low_level_hash.cc",
				"absl/log/die_if_null.cc",
				"absl/log/flags.cc",
				"absl/log/globals.cc",
				"absl/log/initialize.cc",
				"absl/log/internal/check_op.cc",
				"absl/log/internal/conditions.cc",
				"absl/log/internal/fnmatch.cc",
				"absl/log/internal/globals.cc",
				"absl/log/internal/log_format.cc",
				"absl/log/internal/log_message.cc",
				"absl/log/internal/log_sink_set.cc",
				"absl/log/internal/nullguard.cc",
				"absl/log/internal/proto.cc",
				"absl/log/log_entry.cc",
				"absl/log/log_sink.cc",
				"absl/numeric/int128.cc",
				"absl/profiling/internal/exponential_biased.cc",
				"absl/profiling/internal/periodic_sampler.cc",
				"absl/random/discrete_distribution.cc",
				"absl/random/gaussian_distribution.cc",
				"absl/random/internal/chi_square.cc",
				"absl/random/internal/distribution_test_util.cc",
				"absl/random/internal/pool_urbg.cc",
				"absl/random/internal/randen.cc",
				"absl/random/internal/randen_detect.cc",
				"absl/random/internal/randen_hwaes.cc",
				"absl/random/internal/randen_round_keys.cc",
				"absl/random/internal/randen_slow.cc",
				"absl/random/internal/seed_material.cc",
				"absl/random/seed_gen_exception.cc",
				"absl/random/seed_sequences.cc",
				"absl/status/internal/status_internal.cc",
				"absl/status/status.cc",
				"absl/status/status_payload_printer.cc",
				"absl/status/statusor.cc",
				"absl/strings/ascii.cc",
				"absl/strings/charconv.cc",
				"absl/strings/cord.cc",
				"absl/strings/cord_analysis.cc",
				"absl/strings/cord_buffer.cc",
				"absl/strings/escaping.cc",
				"absl/strings/internal/charconv_bigint.cc",
				"absl/strings/internal/charconv_parse.cc",
				"absl/strings/internal/cord_internal.cc",
				"absl/strings/internal/cord_rep_btree.cc",
				"absl/strings/internal/cord_rep_btree_navigator.cc",
				"absl/strings/internal/cord_rep_btree_reader.cc",
				"absl/strings/internal/cord_rep_consume.cc",
				"absl/strings/internal/cord_rep_crc.cc",
				"absl/strings/internal/cordz_functions.cc",
				"absl/strings/internal/cordz_handle.cc",
				"absl/strings/internal/cordz_info.cc",
				"absl/strings/internal/cordz_sample_token.cc",
				"absl/strings/internal/damerau_levenshtein_distance.cc",
				"absl/strings/internal/escaping.cc",
				"absl/strings/internal/memutil.cc",
				"absl/strings/internal/ostringstream.cc",
				"absl/strings/internal/pow10_helper.cc",
				"absl/strings/internal/str_format/arg.cc",
				"absl/strings/internal/str_format/bind.cc",
				"absl/strings/internal/str_format/extension.cc",
				"absl/strings/internal/str_format/float_conversion.cc",
				"absl/strings/internal/str_format/output.cc",
				"absl/strings/internal/str_format/parser.cc",
				"absl/strings/internal/stringify_sink.cc",
				"absl/strings/internal/utf8.cc",
				"absl/strings/match.cc",
				"absl/strings/numbers.cc",
				"absl/strings/str_cat.cc",
				"absl/strings/str_replace.cc",
				"absl/strings/str_split.cc",
				"absl/strings/substitute.cc",
				"absl/synchronization/barrier.cc",
				"absl/synchronization/blocking_counter.cc",
				"absl/synchronization/internal/create_thread_identity.cc",
				"absl/synchronization/internal/futex_waiter.cc",
				"absl/synchronization/internal/graphcycles.cc",
				"absl/synchronization/internal/kernel_timeout.cc",
				"absl/synchronization/internal/per_thread_sem.cc",
				"absl/synchronization/internal/pthread_waiter.cc",
				"absl/synchronization/internal/sem_waiter.cc",
				"absl/synchronization/internal/stdcpp_waiter.cc",
				"absl/synchronization/internal/waiter_base.cc",
				"absl/synchronization/internal/win32_waiter.cc",
				"absl/synchronization/mutex.cc",
				"absl/synchronization/notification.cc",
				"absl/time/civil_time.cc",
				"absl/time/clock.cc",
				"absl/time/duration.cc",
				"absl/time/format.cc",
				"absl/time/time.cc",
			],
			publicHeadersPath: "include"
		),
	],
	cLanguageStandard: .gnu11,
	cxxLanguageStandard: .gnucxx20
)
